#!/usr/bin/env bash
# Render nginx peer upstream lines for OD daemon userId hash routing (39_2 §4).
#
# Discovers sibling teamver-design EC2 instances (same Service tag + environment)
# and writes /etc/nginx/conf.d/teamver-design-od-daemon-peers.inc.conf with:
#   server <private-ip>:7456 max_fails=2 fail_timeout=10s;
#
# Single-node: file contains comments only — upstream hash still works (local only).
#
# Usage:
#   sudo bash scripts/render_od_daemon_peers_nginx.sh
#   sudo bash scripts/render_od_daemon_peers_nginx.sh --dry-run
#   OD_DAEMON_PEER_PORT=7456 bash scripts/render_od_daemon_peers_nginx.sh
#
# Env:
#   AWS_REGION / AWS_DEFAULT_REGION
#   TEAMVER_DESIGN_SERVICE_TAG (default teamver-design)
#   TEAMVER_DESIGN_ENV_TAG       (default from ENV in .env.staging|.env.production)
#   OD_DAEMON_PEER_PORT          (default 7456)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="${OD_DAEMON_PEERS_NGINX_CONF:-/etc/nginx/conf.d/teamver-design-od-daemon-peers.inc.conf}"
DRY_RUN=false
PEER_PORT="${OD_DAEMON_PEER_PORT:-7456}"
SERVICE_TAG="${TEAMVER_DESIGN_SERVICE_TAG:-teamver-design}"

usage() {
  cat <<'EOF'
render_od_daemon_peers_nginx.sh — peer OD daemon lines for nginx hash upstream

  sudo bash scripts/render_od_daemon_peers_nginx.sh [--dry-run]

Requires: aws CLI + EC2 instance profile (or AWS creds) on the Design host.
EOF
}

while (( $# )); do
  case "$1" in
    --dry-run) DRY_RUN=true ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown: $1" >&2; usage; exit 1 ;;
  esac
  shift
done

resolve_self_instance_id() {
  local token=""
  token="$(
    curl -sS -m 2 -H 'X-aws-ec2-metadata-token-ttl-seconds: 60' \
      -X PUT http://169.254.169.254/latest/api/token 2>/dev/null || true
  )"
  if [[ -n "$token" ]]; then
    curl -sS -m 2 -H "X-aws-ec2-metadata-token: $token" \
      http://169.254.169.254/latest/meta-data/instance-id 2>/dev/null || true
  fi
}

resolve_env_tag() {
  if [[ -n "${TEAMVER_DESIGN_ENV_TAG:-}" ]]; then
    echo "$TEAMVER_DESIGN_ENV_TAG"
    return
  fi
  if [[ -f "$ROOT/.env.production" ]]; then
    # shellcheck disable=SC1091
    set -a; source "$ROOT/.env.production"; set +a
    if [[ "${ENV:-}" == "production" || "${ENV:-}" == "prod" ]]; then
      echo "prod"
      return
    fi
  fi
  if [[ -f "$ROOT/.env.staging" ]]; then
    echo "staging"
    return
  fi
  echo "staging"
}

REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-ap-northeast-2}}"
SELF_ID="$(resolve_self_instance_id)"
ENV_TAG="$(resolve_env_tag)"

if ! command -v aws >/dev/null 2>&1; then
  echo "⚠️ aws CLI not found — skipping peer render (single-node assumed)"
  exit 0
fi

if [[ -z "$SELF_ID" ]]; then
  echo "⚠️ not on EC2 (no IMDS instance-id) — skipping peer render"
  exit 0
fi

query='Reservations[].Instances[].[InstanceId,PrivateIpAddress,State.Name,Tags[?Key==`Env`].Value|[0],Tags[?Key==`Service`].Value|[0]]'

peer_lines=()
while IFS=$'\t' read -r iid priv state env_tag svc_tag; do
  [[ -z "${iid:-}" ]] && continue
  [[ "$iid" == "$SELF_ID" ]] && continue
  [[ -z "${priv:-}" || "$priv" == "None" ]] && continue
  peer_lines+=( "server ${priv}:${PEER_PORT} max_fails=2 fail_timeout=10s;" )
done < <(
  aws ec2 describe-instances \
    --region "$REGION" \
    --filters \
      "Name=tag:Service,Values=${SERVICE_TAG}" \
      "Name=tag:Env,Values=${ENV_TAG}" \
      "Name=instance-state-name,Values=running,pending" \
    --query "$query" \
    --output text 2>/dev/null || true
)

tmp="$(mktemp)"
{
  echo "# Generated by render_od_daemon_peers_nginx.sh at $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo "# self=$SELF_ID env=$ENV_TAG service=$SERVICE_TAG region=$REGION"
  echo "# Peer OD daemons for nginx hash \$teamver_user_id (docs-teamver/39_2 §4)."
  if (( ${#peer_lines[@]} == 0 )); then
    echo "# No peer backends — single-node or siblings not yet running."
  else
    printf '%s\n' "${peer_lines[@]}"
  fi
} > "$tmp"

if [[ "$DRY_RUN" == true ]]; then
  cat "$tmp"
  rm -f "$tmp"
  echo "DRYRUN: would write → $TARGET (${#peer_lines[@]} peer(s))"
  exit 0
fi

if [[ ! -d "$(dirname "$TARGET")" ]]; then
  echo "❌ target directory missing: $(dirname "$TARGET") (run on EC2 with nginx installed)"
  rm -f "$tmp"
  exit 1
fi

install -m 0644 "$tmp" "$TARGET"
rm -f "$tmp"
echo "✓ wrote $TARGET (${#peer_lines[@]} peer backend(s))"

if command -v nginx >/dev/null 2>&1 && nginx -t >/dev/null 2>&1; then
  systemctl reload nginx 2>/dev/null || nginx -s reload 2>/dev/null || true
fi
