import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const here = dirname(fileURLToPath(import.meta.url));
const fileViewer = readFileSync(join(here, '../../src/components/FileViewer.tsx'), 'utf8');
const projectView = readFileSync(join(here, '../../src/components/ProjectView.tsx'), 'utf8');

describe('FileViewer revision tip advance after undo', () => {
  it('paints target revision HTML and freeze when activeSequence moves the cursor', () => {
    const start = fileViewer.indexOf('const refreshRevisionStack = useCallback');
    expect(start).toBeGreaterThan(0);
    const block = fileViewer.slice(start, start + 7_000);
    expect(block).toContain('resolveRevisionCursorId');
    expect(block).toContain('getActiveRevisionSequence');
    expect(block).toContain('cursorMovedByActiveSequence');
    expect(block).toContain('manualEditPinnedSourceRef.current = null');
    expect(block).toContain('resolveRevisionSnapshotContent');
    expect(block).toContain('setManualEditFrozenSource');
    expect(block).toContain('activeMissingFromList');
    expect(block).toContain('revisionRefreshGenerationRef');
    // Tip advance with identical HTML skips setSource/ref/gate + freeze remount /
    // reloadKey / repair-cache / draft churn.
    expect(block).toContain('contentUnchanged');
    expect(block).toContain('if (!contentUnchanged)');
    expect(block).toContain('rememberStablePreviewSource(projectId, file.name, targetHtml)');
    const unchangedGuard = block.indexOf('if (!contentUnchanged)');
    expect(unchangedGuard).toBeGreaterThan(0);
    expect(block.indexOf('rememberStablePreviewSource(projectId, file.name, targetHtml)')).toBeGreaterThan(
      unchangedGuard,
    );
    expect(block.indexOf('setSource(targetHtml)')).toBeGreaterThan(unchangedGuard);
    // Unchanged branch syncs drifted freeze/gate/stable via refs (not stale state).
    expect(block).toContain('manualEditFrozenSourceRef.current !== targetHtml');
    expect(block).toContain('lastStablePreviewSourceRef.current !== targetHtml');
    expect(block).toContain('exportHtmlSnapshotGateRef.current !== targetHtml');
    expect(block).toContain('current.fullSource === targetHtml');
    expect(block).not.toContain('hydratedUndoCursorFromSession');
    // liveHtml mount shares one intact-gated repair across source/stable/paints.
    expect(fileViewer).toContain('initialLiveHtmlRepaired');
    expect(fileViewer).toContain('repairArtifactDocumentHeadIfNeeded');
    expect(fileViewer).toContain('readCachedPreviewSource');
    expect(fileViewer).toContain('rememberStablePreviewSource');
    expect(fileViewer).toContain('acceptPreviewHtmlCandidate');
    // remove-element remaining multi-select shares one Document.
    expect(fileViewer).toContain('One Document for remaining multi-select inspector after remove');
    expect(fileViewer).toContain('remainingDoc');
    // remove-element 2→1 seeds inspector from remaining snapshot (not empty draft).
    expect(fileViewer).toContain('2→1: seed inspector from the remaining target snapshot');
    expect(fileViewer).toContain('manualEditTargetsIdentityFingerprint');
    expect(fileViewer).toContain('listProjectFileRevisionsSoftCached');
    expect(fileViewer).toContain('Multi-select inspector: reparse on id-set OR selected identity change');
    expect(fileViewer).toContain('export function rememberStablePreviewSource');
    // Group geometry builders forward their shared Document into batch apply.
    expect(fileViewer).toContain('buildGroupMoveStylePatches(');
    expect(fileViewer).toContain('buildGroupResizeStylePatches(');
    expect(fileViewer).toContain('buildGroupGeometryPatches(baseSource, updates)');
    expect(fileViewer).toMatch(
      /applyManualEditBatch\(\s*patches,\s*groupMoveHistoryLabel\(targets\.length\),\s*parsedDoc/,
    );
    expect(fileViewer).toMatch(
      /applyManualEditBatch\(\s*patches,\s*groupResizeHistoryLabel\(targets\.length\),\s*parsedDoc/,
    );
    expect(fileViewer).toContain('applyManualEditBatch(patches, label, parsedDoc)');
  });

  it('shares one Document for style-cancel and multi-select inspector refresh', () => {
    expect(fileViewer).toContain('function cancelManualEditStyleDraft()');
    const cancelStart = fileViewer.indexOf('function cancelManualEditStyleDraft()');
    const cancelBlock = fileViewer.slice(cancelStart, cancelStart + 1_600);
    expect(cancelBlock).toContain('parseManualEditSource(base)');
    expect(cancelBlock).toContain('inspectorManualEditStyles');
    expect(fileViewer).toContain('One Document for snapshot + multi-select inspector merge');
    expect(fileViewer).toContain('One Document for style read + no-op reconcile');
    expect(fileViewer).toContain('reconcileManualEditDraftAfterNoOpFlush(pending, parsedDoc)');
    expect(fileViewer).toContain('readManualEditTargetSnapshot(base, primary.id, {}, parsedDoc)');
    expect(fileViewer).toContain('One Document for multi-target diff + no-op reconcile / apply');
    expect(fileViewer).toContain('applyManualEditBatch(patches, pending.label, parsedDoc)');
    expect(fileViewer).toContain('One Document for style read + no-op reconcile + apply');
    expect(fileViewer).toContain('parsedDoc: sharedParsedDoc');
  });

  it('uses optimistic stackWithPushedRevision after manual/inspect push', () => {
    expect(fileViewer).toContain('stackWithPushedRevision');
    expect(fileViewer).toMatch(
      /stackWithPushedRevision\(\s*revisionStackRef\.current,\s*saved\.revision/,
    );
    // Local tip push skips immediate list GET (optimistic stack already matches).
    expect(fileViewer).toContain('Optimistic tip already matches the push — skip immediate list GET');
    expect(fileViewer).toContain('Deferred refresh catches retention/conflict shortly after');
    expect(fileViewer).toContain('scheduleDeferredRevisionStackRefresh');
    expect(fileViewer).toContain('Coalesce tip-push deferred list GET');
    expect(fileViewer).toContain('REVISION_LIST_SOFT_CACHE_OPTIMISTIC_TTL_MS');
    expect(fileViewer).toContain('{ optimistic: true }');
    expect(fileViewer).toContain('pinManualEditSavedSource(next)');
    expect(fileViewer).toContain('isManualEditSourcePinActive(manualEditPinnedSourceRef.current)');
    expect(fileViewer).toContain('When tip content cache already differs from the pin');
    expect(fileViewer).toContain('activeSeqMissingFromStack');
    expect(fileViewer).toContain('tipContentForManualEditSavePin');
    expect(fileViewer).not.toContain('readTipContentForManualEditSavePin');
    expect(fileViewer).toContain('resolveManualEditSourceAgainstPinAndTip');
    expect(fileViewer).toContain('preferTipWhenCandidateLags: false');
    expect(fileViewer).toContain('preferTipWhenCandidateLags: shouldPreferTipWhenCandidateLags({');
    expect(fileViewer).toContain('suppressUntilRefresh: manualEditSuppressTipPreferUntilRefreshRef.current');
    expect(fileViewer).toContain('Tip yield / pin prefer — paint before edit-mode disk hold');
    expect(fileViewer).toContain('shouldEarlyPaintResolvedPinTipSource');
    expect(fileViewer).toContain('Unstable tip must not early-paint');
    expect(fileViewer).toContain('acceptedKeepsEarlyPaintTipOrPin');
    expect(fileViewer).toContain('Route tip/pin through accept so lastStable stays consistent');
    expect(fileViewer).toContain('acceptPreviewHtmlCandidate(\n              repairedTipOrPin');
    expect(fileViewer).toContain('shouldSyncManualEditFrozenSourceToPainted');
    expect(fileViewer).toContain('Tip yield only — do NOT remount freeze on ordinary liveHtml');
    expect(fileViewer).toContain('Tip yield while editing must remount freeze');
    expect(fileViewer).toContain('shouldEchoManualEditSelectionAfterFreezeSync');
    expect(fileViewer).toContain('shouldRequestTipRemountRemasureAfterSrcDocLoad');
    expect(fileViewer).toContain('requestTipRemountRemasureAfterSrcDocLoad');
    expect(fileViewer).toContain('shouldApplyTipRemountSyncHostMeasureOnSrcDocLoad');
    expect(fileViewer).toContain('applyTipRemountSyncHostMeasureAfterSrcDocLoad');
    expect(fileViewer).toContain('applyTipRemountSyncHostMeasureAfterSrcDocLoadWithRetry');
    expect(fileViewer).toContain('shouldRetryTipRemountSyncHostMeasureAfterSrcDocLoad');
    expect(fileViewer).toContain('shouldCancelTipRemountSyncHostMeasureRetry');
    expect(fileViewer).toContain('manualEditTipRemountSyncRetryRafRef');
    expect(fileViewer).toContain('Drop stale onLoad sync retry from a prior tip-yield');
    expect(fileViewer).toContain('shouldReleaseTipRemountChromeAfterSyncHostMeasure');
    expect(fileViewer).toContain('First load tick often measures before fonts/deck-fit layout');
    expect(fileViewer).toContain('Tip-yield: sync tip rect');
    expect(fileViewer).toContain('drop inert; keep grace for wild-jump until async remasure');
    expect(fileViewer).toContain('shouldArmTipRemountFitSettleForDeckHostFit');
    expect(fileViewer).toContain('shouldRemeasureTipRemountAfterDeckHostFitSettle');
    expect(fileViewer).toContain('scheduleTipRemountRemasureAfterDeckHostFitSettle');
    expect(fileViewer).toContain('shouldScheduleTipRemountFitSettleRemasureOnLoad');
    expect(fileViewer).toContain('Sticky deck fit may arm settle while needsFit is false');
    expect(fileViewer).toContain('remeasureTipRemountAfterDeckHostFitSettle');
    expect(fileViewer).toContain('shouldDeferTipRemountGraceConsumeForDeckHostFitSettle');
    expect(fileViewer).toContain('shouldSkipWildJumpDuringTipRemountFitSettle');
    expect(fileViewer).toContain('shouldSkipWildJumpForTipRemountSelectedMember');
    expect(fileViewer).toContain('shouldSkipWildJumpDuringTipRemountFitSettleForSelectedMember');
    expect(fileViewer).toContain('shouldRefreshHostMetricsAfterTipRemountMultiRemasure');
    expect(fileViewer).toContain('refreshManualEditHostMetricsAfterTipRemountMulti');
    expect(fileViewer).toContain('Multi: force host metrics so union chrome');
    expect(fileViewer).toContain('Multi tip-yield: sibling members share the tip-remount session');
    expect(fileViewer).toContain('Selection echo / remasure: srcDoc onLoad');
    expect(fileViewer).toContain('Tip-yield: sync tip rect, then async remasure on the live tip document');
    expect(fileViewer).toContain('do NOT depend on manualEditFrozenSource');
    expect(fileViewer).toContain('shouldSkipSrcDocTransportRemountForManualEditFreezeTipSync');
    expect(fileViewer).toContain('Tip-yield freeze already reloads via srcDoc');
    expect(fileViewer).toContain('shouldDisableManualEditChromeUntilTipRemasure');
    expect(fileViewer).toContain('Inert chrome until remasure');
    expect(fileViewer).toContain('Tip-remount: keep chrome mounted inert at last rect');
    expect(fileViewer).toContain('Tip-remount: keep multi chrome mounted inert at last union rect');
    expect(fileViewer).toContain('disabled={manualEditInlineTextEditing || manualEditTipRemountChromeInert}');
    expect(fileViewer).toContain('Apply tip geometry before releasing chrome suppress');
    expect(fileViewer).not.toContain(
      '&& !shouldSuppressManualEditChromeUntilTipRemasure(manualEditTipRemountChromeSuppressed)',
    );
    expect(fileViewer).toContain('abortManualEditGestureForTipYieldFreezeSync');
    expect(fileViewer).toContain('shouldAbortManualEditGestureForTipYieldFreezeSync');
    expect(fileViewer).toContain('Tip remount would drop host overlays mid-drag');
    expect(fileViewer).toContain('shouldPostHostChromeDuringTipRemountSuppress');
    expect(fileViewer).toContain('const hostChrome = shouldPostHostChromeDuringTipRemountSuppress(');
    expect(fileViewer).toContain('manualEditTipRemountChromeSuppressed');
    expect(fileViewer).toContain('manualEditTipRemountChromeSafetyTimeoutRef');
    expect(fileViewer).toContain('Escape hatch: remasure never arrives');
    expect(fileViewer).toContain('shouldReleaseTipRemountChromeOnFailedRemasure');
    expect(fileViewer).toContain('Failed tip remasure — release suppress so handles are not stuck');
    expect(fileViewer).toContain('shouldPatchSelectedGeometryFromTargetsBroadcast');
    expect(fileViewer).toContain('Identity unchanged — still patch selected rects');
    expect(fileViewer).toContain('Source-only Mixed — same plan helper as tip-yield / remove');
    expect(fileViewer).toContain('scheduleManualEditSelectionEchoAfterFreezeSync');
    expect(fileViewer).toContain('Keep warm stack until refreshRevisionStack lands');
    expect(fileViewer).toContain('shouldClearTipContentCacheAfterConfirmRefuse');
    expect(fileViewer).toContain('clearRevisionContentCacheEntry');
    expect(fileViewer).toContain('shouldPreferTipWhenCandidateLags');
    expect(fileViewer).toContain('manualEditSuppressTipPreferUntilRefreshRef');
    expect(fileViewer).toContain('nextTipPreferSuppressState');
    expect(fileViewer).toContain('Artifact switch: cancel confirm-refuse tip-prefer suppress');
    expect(fileViewer).toContain('Generation bump cancels refresh before commit/give-up');
    expect(fileViewer).toContain('Generation mismatch: keep tip-prefer suppress latch');
    expect(fileViewer).toContain('shouldReseedManualEditMultiInspectorAfterFreezeSync');
    expect(fileViewer).toContain('Source-only reseed (same plan helper as batch flush / cancel) — 기획 59');
    expect(fileViewer).toContain('Tip Mixed must not merge preview target.styles');
    expect(fileViewer).toContain("shouldReadMultiInspectorStylesFromSourceOnly('tip-yield')");
    expect(fileViewer).toContain('resolveTipYieldIdentityStyles');
    expect(fileViewer).toContain('Tip source wins — do not merge pre-tip preview styles');
    expect(fileViewer).toContain('concurrentPendingOwnsTipYieldReseedStyles');
    expect(fileViewer).toContain('Never clobber in-flight draft styles while pending owns the panel');
    expect(fileViewer).toContain('shouldClearMixedKeysAfterTipYieldReseedSkip');
    expect(fileViewer).toContain('2→1 / clear during deferred tip-yield — drop stale Mixed');
    expect(fileViewer).toContain('shouldReseedSingleInspectorAfterTipYieldMixedClear');
    expect(fileViewer).toContain('Mixed→single: reseed inspector from painted source');
    expect(fileViewer).toContain('readManualEditTargetSnapshot(base, seedId');
    expect(fileViewer).toContain('shouldApplyTipYieldSingleInspectorSnapshot');
    expect(fileViewer).toContain('Tip source may have dropped the node — do not wipe styles/fields');
    expect(fileViewer).toContain('shouldRefreshHostPaintAfterTipYieldSingleReseed');
    expect(fileViewer).toContain('2→1 tip-yield: host paint may still track the prior multi primary');
    expect(fileViewer).toContain('Skip while tip-remount grace is active');
    expect(fileViewer).toContain('shouldSyncSelectedTargetIdentityAfterTipYieldSingleReseed');
    expect(fileViewer).toContain('Keep selected target identity aligned with painted tip');
    expect(fileViewer).toContain('Also refresh manualEditTargets membership for the same seed');
    expect(fileViewer).toContain('setManualEditTargets((current) => {');
    expect(fileViewer).toContain('const nextList = current.map((item) => {');
    expect(fileViewer).toContain('shouldRefreshHostPaintAfterTipRemountRemasure');
    expect(fileViewer).toContain('applyManualEditMeasuredGeometry(measured)');
    expect(fileViewer).toContain('Full-merge was unused and would clobber styles/text');
    expect(fileViewer).toContain('identity refreshes flow through od-edit-targets');
    expect(fileViewer).toContain('shouldConsumeTipRemountGeometryGraceOnRemasure');
    expect(fileViewer).toContain('Sibling remasure must not consume primary grace');
    expect(fileViewer).toContain('const consumeGrace = shouldConsumeTipRemountGeometryGraceOnRemasure');
    expect(fileViewer).toContain('if (consumeGrace)');
    expect(fileViewer).toContain('shouldRefreshHostPaintAfterTipRemountRemasure(true)');
    expect(fileViewer).toContain('Apply tip geometry before releasing chrome suppress');
    expect(fileViewer).toContain('Multi tip-yield reseed and Mixed→single both arm tip-remount grace');
    expect(fileViewer).toContain('manualEditSelectedIdentityFingerprintRef.current =');
    expect(fileViewer).toContain('manualEditTargetsIdentityFingerprintRef.current =');
    expect(fileViewer).toContain('Avoid redundant identity reseed on the next bridge broadcast');
    expect(fileViewer).toContain('Selection commit owns selected-set identity');
    expect(fileViewer).toContain('Keep selected-set fingerprint aligned after membership shrink');
    expect(fileViewer).toContain('refreshManualEditHostPaintRect(measured.id, { force: true })');
    expect(fileViewer).toContain('refreshManualEditHostPaintRect(paintId, { force: true })');
    expect(fileViewer).toContain('clearManualEditTipRemountGeometryGraceIfNeeded');
    expect(fileViewer).toContain('clearManualEditTipRemountGeometryGrace(');
    expect(fileViewer).toContain('shouldClearTipRemountGeometryGraceOnExpiry');
    expect(fileViewer).toContain('shouldClearTipRemountGeometryGraceOnSelectionChange');
    expect(fileViewer).toContain('Selection left tip-remount grace primary');
    expect(fileViewer).toContain('shouldSkipWildJumpAfterTipRemountGrace');
    expect(fileViewer).toContain('Expired grace: clear latch (id + until) so wild-jump deny is restored');
    expect(fileViewer).toContain('manualEditTipRemountGeometryGraceIdRef');
    expect(fileViewer).toContain('selectedManualEditTargetIdRef.current');
    expect(fileViewer).toContain('Accept fell back — soft-retry before edit-mode hold');
    expect(fileViewer).toContain('Confirm-refuse suppress ends once warm stack is replaced');
    expect(fileViewer).toContain('activeTipResolvedHtml');
    expect(fileViewer).toContain('Cold tip cache: snapshot/cache resolve IS tip content');
    expect(fileViewer).toContain('activeSeq miss → null (no HEAD fallback) so cold tip remount can adopt');
    expect(fileViewer).toContain('manualEditHistoryConfirmTrustsLocal(');
    expect(fileViewer).toContain('manualEditHistoryConfirmCanSkipDiskFetch(');
    expect(fileViewer).toContain('Tip≠expected forces GET');
    expect(fileViewer).toContain('Tip≠expected forces confirm even in edit mode');
    expect(fileViewer).toContain('no false "external change"');
    expect(fileViewer).toContain('Tip/external refresh — adopt disk into source + freeze together');
    expect(fileViewer).toContain('Source-only reseed (same plan helper as batch flush / cancel)');
    expect(fileViewer).toContain('shouldSyncSelectedTargetsIdentityAfterTipYieldMultiReseed');
    expect(fileViewer).toContain('Multi tip-yield: sync identity for every selected id from painted tip');
    expect(fileViewer).toContain('Always refresh primary fields from tip when snapshot is usable');
    expect(fileViewer).toContain('Pending owns styles — still align primary text fields with tip');
    expect(fileViewer).toContain('planManualEditMultiInspectorReseed');
    expect(fileViewer).toContain("shouldReadMultiInspectorStylesFromSourceOnly(\n              'od-edit-targets'");
    expect(fileViewer).toContain('tipRemountSessionActive');
    expect(fileViewer).toContain('shouldSkipOdEditTargetsIdentityMixedReseedDuringTipRemount');
    expect(fileViewer).toContain('shouldAllowOdEditTargetsPendingReseedDuringTipProtect');
    expect(fileViewer).toContain('allowPendingReseed');
    expect(fileViewer).toContain('Pending drafts stay reachable during tip protect');
    expect(fileViewer).toContain('withPreservedTipSyncedStylesOnBridgeTarget');
    expect(fileViewer).toContain('resolveTipSyncedStylesForOdEditTargetsPreserve');
    expect(fileViewer).toContain('withPreservedTipSyncedIdentityOnBridgeTarget');
    expect(fileViewer).toContain('resolveTipSyncedTargetForOdEditTargetsPreserve');
    expect(fileViewer).toContain('manualEditTargetsRef');
    expect(fileViewer).toContain('skipIdentityMixedReseed');
    expect(fileViewer).toContain('Tip-remount: preserve tip-synced identity on the selected set');
    expect(fileViewer).toContain('skip identity-only churn');
    expect(fileViewer).toContain('nextTipRemountIdentityHoldUntilMs');
    expect(fileViewer).toContain('manualEditTipRemountIdentityHoldUntilRef');
    expect(fileViewer).toContain('shouldReadSingleInspectorStylesFromSourceOnlyForOdEditTargets');
    expect(fileViewer).toContain('Source-only — bridge preview merge flickers tip settle-exit');
    expect(fileViewer).toContain('fingerprint the catalog we will store');
    expect(fileViewer).toContain('shouldArmTipRemountIdentityHoldOnGraceClear');
    expect(fileViewer).toContain('shouldPreserveTipSyncedStylesOnOdEditTargets');
    expect(fileViewer).toContain("clearManualEditTipRemountGeometryGrace('selection')");
    expect(fileViewer).toContain("clearManualEditTipRemountGeometryGrace('consume')");
    expect(fileViewer).toContain('selectionIdsChangedEarly');
    expect(fileViewer).toContain("shouldReadMultiInspectorStylesFromSourceOnly('cancel')");
    expect(fileViewer).toContain("shouldReadMultiInspectorStylesFromSourceOnly('noop-flush')");
    expect(fileViewer).toContain('styleDraftPending');
    expect(fileViewer).toContain('Pending style draft owns the inspector');
    expect(fileViewer).toContain('Pending styles own the panel — refresh field identity only');
    expect(fileViewer).toContain('Multi + pending: keep draft styles; refresh fields + mixedKeys only');
    expect(fileViewer).toContain('mixedKeysForPendingStyleDraft');
    expect(fileViewer).toContain('Suppress Mixed on keys the user is actively drafting');
    expect(fileViewer).toContain('Multi-select: recompute mixedKeys from saved source');
    expect(fileViewer).toContain('concurrentPending');
    expect(fileViewer).toContain('Source-only styles');
    expect(fileViewer).toContain('planManualEditMultiInspectorReseed');
    expect(fileViewer).toContain('selectedTargetsIdentityChanged');
    expect(fileViewer).toContain('manualEditSelectedIdentityFingerprintRef');
    expect(fileViewer).toContain("from '../edit-mode/manual-edit-targets-identity'");
    expect(fileViewer).toContain('manualEditTargetsIdentityFingerprint');
    expect(fileViewer).toContain('Warm soft-cache so tip-lag disk soft-retries reuse this list');
    expect(fileViewer).toContain('Prefer active → head → tip');
    expect(fileViewer).toContain('warmRevisionListSoftCacheFromList(projectId, file.name, softSeq, list)');
    expect(fileViewer).toContain('Cheap preflight — most decks never host inspect overrides');
    expect(fileViewer).toContain('\\bdata-od-inspect-overrides\\b');
    expect(fileViewer).toContain('Echo selected-target only when membership changes');
    expect(fileViewer).toContain('Single-select: identity field change');
    expect(fileViewer).toContain('Active pin owns the painted frame — adopt pin if paint drifted');
    expect(fileViewer).toContain('warmRevisionListSoftCacheFromStack');
    expect(fileViewer).toContain('image-set\\s*\\(|element\\s*\\(|-moz-binding|javascript\\s*:|vbscript\\s*:|data\\s*:');
    expect(fileViewer).toContain('inspectOverrideValueIsUnsafe');
    expect(fileViewer).toContain('normalizeCssForSafetyScan');
    expect(fileViewer).toContain('Multi-select inspector: reparse on id-set OR selected identity change');
    expect(fileViewer).toContain('Equal geometry — keep prior reference');
    expect(fileViewer).toContain('current.fullSource === contentToSave ? current');
    expect(fileViewer).toContain('Geometry-only rebroadcasts for the same id skip React churn');
    expect(fileViewer).toContain('const contentUnchanged = sourceRef.current === nextSource');
    expect(fileViewer).toContain('const paintSource = acceptedPaint');
    expect(fileViewer).toContain('if (sourceRef.current !== paintSource)');
    expect(fileViewer).toContain('if (sourceRef.current !== accepted)');
    expect(fileViewer).toContain('manualEditFrozenSource,');
    expect(fileViewer).toContain('Idle remasure only: reject wild jumps');
    expect(fileViewer).toContain('manualEditGeometryIsWildJump');
    expect(fileViewer).toContain('applyManualEditMeasuredGeometry(measured)');
    expect(fileViewer).toContain('isHandoffRect');
    expect(fileViewer).toContain('if (!measured || isHandoffRect) {');
    expect(fileViewer).toContain('Failed tip remasure — release suppress so handles are not stuck');
    expect(fileViewer).toContain('Always complete awaiters (gesture waiters)');
    expect(fileViewer).toContain('Gesture session: awaiter done; never idle remasure / wild-jump');
    expect(fileViewer).toContain('Still expire tip grace so chrome suppress cannot stick behind a drag');
    expect(fileViewer).toContain('settleManualEditGeometryHandoff');
    const confirmStart = fileViewer.indexOf('async function confirmManualEditHistorySource');
    expect(confirmStart).toBeGreaterThan(0);
    const confirmBlock = fileViewer.slice(confirmStart, confirmStart + 3_800);
    expect(confirmBlock.indexOf('tipContentForManualEditSavePin')).toBeLessThan(
      confirmBlock.indexOf('manualEditHistoryConfirmCanSkipDiskFetch'),
    );
    expect(confirmBlock).toContain('manualEditHistoryConfirmTrustsLocal(');
    expect(confirmBlock).toContain('tipContent');
    expect(confirmBlock).toContain('Keep warm stack until refreshRevisionStack lands');
    expect(confirmBlock).toContain('scheduleManualEditSelectionEchoAfterFreezeSync');
    expect(confirmBlock).toContain('shouldClearTipContentCacheAfterConfirmRefuse');
    expect(confirmBlock).toContain("nextTipPreferSuppressState(\n      'confirm-refuse'");
    // Confirm refuse must not wipe stack empty before refresh (tip cursor race).
    expect(confirmBlock).not.toContain('createRevisionStackSnapshot([], null)');
    expect(fileViewer).toContain('live→raw hold: skip setSource when already painting stable');
    expect(fileViewer).toContain('Undo demotes activeSeq — warm soft-cache for the restored tip');
    expect(fileViewer).toContain('srcdoc path updates via setSource; URL-load still needs reloadKey bust');
    expect(fileViewer).toContain('if (useUrlLoadPreview)');
    expect(fileViewer).toContain('if (useUrlLoadPreview) setReloadKey');
    expect(fileViewer).toContain('warmRevisionListSoftCacheFromList');
    expect(fileViewer).toContain('No-op save — skip push / paint / reloadKey churn');
    expect(fileViewer).toContain('nextActive === manualEditInlineTextEditingRef.current');
    const restoreStart = fileViewer.indexOf('function applyRestoredSourceToViewer');
    expect(restoreStart).toBeGreaterThan(0);
    const restoreBlock = fileViewer.slice(restoreStart, restoreStart + 2_000);
    expect(restoreBlock).toContain('const contentUnchanged = sourceRef.current === sourceToApply');
    expect(restoreBlock).toContain('warmRevisionListSoftCacheFromStack');
    expect(restoreBlock).toContain('srcdoc (edit or preview) updates via setSource');
    expect(restoreBlock).toContain('if (!useUrlLoadPreview)');
    const tipStart = fileViewer.indexOf('const contentUnchanged = targetHtml === sourceRef.current');
    expect(tipStart).toBeGreaterThan(0);
    const tipBlock = fileViewer.slice(tipStart, tipStart + 900);
    expect(tipBlock).toContain('if (useUrlLoadPreview) setReloadKey');
    expect(fileViewer).toContain('Active pin owns the painted frame — adopt pin if paint drifted');
    expect(fileViewer).toContain('Prefer active → head → tip');
    expect(fileViewer).toContain('Re-key soft-cache to the cursor/tip seq');
    expect(fileViewer).toContain('Already on empty page-styles — skip clear/draft wipe churn');
    expect(fileViewer).toContain('Manual-edit is srcdoc — URL-load only needs reloadKey bust');
  });
});

describe('ProjectView agent toast undo', () => {
  it('only offers Undo when parentRevisionId is a string and clears live artifact', () => {
    expect(projectView).toContain('typeof pushedRevision.parentRevisionId === \'string\'');
    const start = projectView.indexOf('typeof pushedRevision.parentRevisionId === \'string\'');
    expect(start).toBeGreaterThan(0);
    const block = projectView.slice(start, start + 1_800);
    expect(block).toContain('setActiveRevisionSequence');
    expect(block).toContain('setArtifact(null)');
    expect(block).not.toContain('persistCommentAttachments.length > 0');
  });
});
